version: 2
formats:
  - htmlzip

python:
  version: 3.6
  install:
    - method: pip
      path: .
    - requirements: .rtfd-requirements.txt


conda:
  environment: .readthedocs-environment.yml

build:
  image: latest
