name: solaris
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pip>=19.0.3
  - affine>=2.3.0
  - albumentations=0.4.3
  - fiona>=1.7.13
  - gdal=3.0.3
  - geopandas>=0.7.0
  - matplotlib>=3.1.2
  - networkx>=2.4
  - opencv>=4.1
  - pandas>=0.25.3
  - pyproj>=2.1
  - pytorch>=1.3.1
  - pyyaml=5.2
  - rasterio>=1.0.23
  - requests=2.22.0
#  - rio-cogeo>=1.1.6
  - rtree>=0.9.3
  - scikit-image>=0.16.2
  - scipy>=1.3.2
  - torchvision>=0.5.0
  - cudatoolkit=9.2
  - tqdm>=4.40.0
  - urllib3>=1.25.7
  - tensorflow-gpu=1.13.1
  - cuda100
  - shapely
  #- pip
  #- pip:
  #  - git+https://github.com/Toblerity/shapely.git@master#egg=shapely-1.7.1dev # temporary, dev required for numpy array support
